@startuml
actor Trader
control OneSplit_Contract


== swap ==

Trader -> OneSplit_Contract: 估算最佳兑换方案
OneSplit_Contract -> OneSplit_Contract: getExpectedReturn()


Trader -> OneSplit_Contract: 执行多DEX兑换交易
OneSplit_Contract -> OneSplit_Contract: swap()

@enduml


